#!/usr/bin/env python3
"""One-shot decoder: emit the three in-slice combat backdrop configs (U4).

Mirrors ``tools/decode_city_map.py`` exactly for the byte format — the combat
backdrops ``ks``/``kp``/``km`` (research ``src/ks``, ``src/kp``, ``src/km``) are the
SAME 2003-byte C64 screen-file layout as ``src/karte``: 1000 screen-code bytes + 1000
color-RAM bytes, both stored bottom-up/right-to-left, plus 3 mode bytes
(border/background/textcolor). The bl loader stores it reversed, so the row-major
codes are ``data[:1000][::-1]`` (``research/tools/render_c64_assets.py:106-119``'s
``parse_screen_file``, which explicitly treats ``COMBAT_OVERLAYS`` — including
ks/kp/km — through the identical ``parse_screen_file``/``render_text_screen`` path
as the text screens).

The runtime must NOT depend on parsing the original binary (KTD-1, mirroring the city
map's own committed-artifact rule), so this ``tools/`` script reads the research source
once and writes plain config artifacts — ``content/combat/<name>.yaml`` — that the
engine loads as data.

Combat only plays out over the FIRST 521 of the 1000 decoded cells (the grid's kept
0..520 bound, ``mf-prg.bas:30145``/``30225``) — rows 14..24 of the loaded screen are
never addressed by the fight loop, so only the first 521 linear codes are emitted
(``engine.combat.CELL_COUNT``).

Run from the engine repo root: ``python tools/decode_combat_backdrops.py``
"""

from __future__ import annotations

from pathlib import Path

import yaml

SCREEN_CODES = 1000
SCREEN_FILE_SIZE = 2003  # 1000 screen codes + 1000 color RAM + 3 mode bytes
GRID_COLS = 40
CELL_COUNT = 521  # engine.combat.CELL_COUNT — the kept 0..520 combat-grid bound

ENGINE_ROOT = Path(__file__).resolve().parent.parent
RESEARCH_ROOT = ENGINE_ROOT.parent / "research"
SRC = RESEARCH_ROOT / "src"
OUT_DIR = (
    ENGINE_ROOT / "data" / "game_configs" / "mafia_1920s" / "content" / "combat"
)

#: The three in-slice combat backdrops (kdh debt-default/collect, and the two other
#: combat-triggering entry points this slice's Assumptions name — ks/kp/km).
BACKDROPS = ("ks", "kp", "km")


def decode_backdrop(path: Path) -> tuple[list[int], list[int], int]:
    """Return (cells[521], color[521], background) for one combat screen file."""
    data = path.read_bytes()
    if len(data) != SCREEN_FILE_SIZE:
        raise ValueError(f"{path.name}: {len(data)} bytes, expected {SCREEN_FILE_SIZE}")
    screen = list(data[:SCREEN_CODES][::-1])
    color = [b & 0x0F for b in data[SCREEN_CODES : SCREEN_CODES * 2][::-1]]
    _border, bg, _textcolor = (b & 0x0F for b in data[SCREEN_CODES * 2 :])
    return screen[:CELL_COUNT], color[:CELL_COUNT], bg


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for name in BACKDROPS:
        src_path = SRC / name
        if not src_path.exists():
            print(f"SKIP {name}: {src_path} not found in research checkout")
            continue
        cells, color, bg = decode_backdrop(src_path)
        payload = {
            "_generated_by": "tools/decode_combat_backdrops.py",
            "_sources": [
                f"../research/src/{name} (data[:1000][::-1], "
                "render_c64_assets.py:106-119 parse_screen_file, mirrored from "
                "decode_city_map.py's karte decode)",
            ],
            "cell_count": CELL_COUNT,
            "cells": cells,
            "color": color,
            "background": bg,
        }
        out_path = OUT_DIR / f"{name}.yaml"
        with out_path.open("w", encoding="utf-8") as fh:
            fh.write(
                "# GENERATED by tools/decode_combat_backdrops.py — do not edit by hand.\n"
                "# Re-run the tool to regenerate from ../research/ sources.\n"
            )
            yaml.safe_dump(payload, fh, sort_keys=False, default_flow_style=None)
        walls = sum(1 for c in cells if c in (160, 156))
        empties = sum(1 for c in cells if c in (32, 96))
        print(
            f"wrote {out_path} ({CELL_COUNT} cells, {walls} wall, {empties} empty, "
            f"{CELL_COUNT - walls - empties} scenery)"
        )
        written += 1
    return written


if __name__ == "__main__":
    n = main()
    print(f"{n}/{len(BACKDROPS)} combat backdrops decoded")
